---
- name: Setup PROD Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/output_vars

    - name: Import PROD setup Variable
      include_vars: vars/prodstacksetup

    - name: Create PROD ec2 key
      ec2_key:
        name: PRODkey
        region: "{{region}}"
      register: PRODkey_out

    - name: Save private key into file loginkey_PROD.pem
      copy:
        content: "{{PRODkey_out.key.private_key}}"
        dest: "./loginkey_PROD.pem"
        mode: 0600
      when: PRODkey_out.changed
